# Generated by Django 3.2.9 on 2021-12-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_account',
        ),
    ]
